# Generated by Django 2.2.7 on 2019-11-29 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20191129_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disk',
            old_name='iface',
            new_name='iface_type',
        ),
    ]
